### ISSUE TITLE
The Component Library docs are a bit awkward to navigate...

### ISSUE THREAD

**Issue by markweitzel** [newrelic/developer-website#442] opened 2020-07-14 17:17 UTC
When you select a component on the left nav, the list re-orients itself to the top, and you lose your place. In addition when the section is opened, the list significantly expands the left nav--again making the orientation a bit awkward.

**Comment by jpvajda** [comment] 2020-07-14 18:43
duplicate of https://github.com/newrelic/developer-website/issues/433. closing

**Closed** 2020-07-14 18:43 UTC
Labels: duplicate, enhancement
