### ISSUE TITLE
Create shared component repository to support both the Devsite and OSS Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#373] opened 2020-07-01 00:47 UTC
**Acceptance Criteria**

- Setup a repo that houses the UI components that are to be shared across the various docs sites. 
- Add a first component to the repo, publish it and consume it from the developer site.

**Assumptions**

1. Developer site, open source site and the general docs site will have UI that is intended to stay aesthetically and functionally consistent across the sites but with content variations. Some of those components are listed here.
2. A pleasant and consistent experience across these subdomains of docs is valuable to New Relic users and to the New Relic brand.
3. The shared components will help prevent a building up tech debt where modifying all the sites requires shotgun surgery across three “same” but in actuality different components in three different repos.

**Comment by jerelmiller** [comment] 2020-07-20 17:52
Duplicate of: 

* https://github.com/newrelic/opensource-website/issues/543
* https://github.com/newrelic/opensource-website/issues/544
* https://github.com/newrelic/developer-website/issues/438
* https://github.com/newrelic/developer-website/issues/439

**Closed by jerelmiller** 2020-07-20 17:52 UTC
Labels: sustaining
